services:
  nginx:
    image: nginx:1.24
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    links:
      - app

  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: ruby/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    links:
      - mysql
      - pgsql
      - memcached
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  mysql:
    image: mysql:8.0
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  pgsql:
    image: postgres:15
    environment:
      - "TZ=Asia/Tokyo"
      - "POSTGRES_USER=isucon"
      - "POSTGRES_PASSWORD=isucon"
      - "POSTGRES_DB=isuconp"
      - "POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C"
    volumes:
      - ./logs/pgsql:/var/log/pgsql
      #- ./sql:/docker-entrypoint-initdb.d
      #- ./etc/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "15432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/pgsql"]

  memcached:
    image: memcached:1.6

volumes:
  mysql:
